# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
style = "blue"
indent = 4
margin = 90

remove_extra_newlines = true

indent_submodule = true

verbose = true

format_markdown = true